name: 'selectors-watcher-action'
description: 'Detect git changes in provided attributes and send notifications to relevant stakeholders'
inputs:
  token: #
    description: ""
    required: true
    default: ""
  slack_channel:  # slack channel ID
    description: 'Slack channel ID to get messages'
    required: true
    default: ''
  slack_token:  # Slack token
    description: 'Slack token'
    required: true
    default: ''
  reviewers: # reviewers names
    description: 'github login user of reviewers you want to add'
    required: false
    default: '[]'
  attributes: # attributes to detect
    description: 'Attribute that we want to detect changes'
    required: false
    default: '[id]'
  slack_users_emails: # Slack users emails in order to be able to mention in the slack channel
    description: "Slack users emails in order to be able to mention in the slack channel"
    required: false
    default: '[]'
runs:
  using: 'node16'
  main: 'dist/index.js'
